# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title bitwise operations 
#' @description
#' bitwise operations  in C++
#' @param a integer 
#' @param b integer
#' @keywords internal
#' @useDynLib prospect
bitAND <- function(aa, bb) {
    .Call('prospect_bitAND', PACKAGE = 'prospect', aa, bb)
}

bitSR <- function(a, b) {
    .Call('prospect_bitSR', PACKAGE = 'prospect', a, b)
}

#' @title Convolve 
#' @description
#' Convolution, written in C++
#' @param X matrix to convolve
#' @param f filter
#' @keywords internal
#' @useDynLib prospect
convCppM <- function(X, f) {
    .Call('prospect_convCppM', PACKAGE = 'prospect', X, f)
}

convCppV <- function(X, f) {
    .Call('prospect_convCppV', PACKAGE = 'prospect', X, f)
}

#' @title A fast distance algorithm for two matrices written in C++ 
#' @usage 
#' fastDist(X,Y,method)
#' @param X a \code{matrix}
#' @param Y a \code{matrix}
#' @param method a \code{string} with possible values "euclid", "cor", "cosine"
#' @return a distance \code{matrix}
#' @keywords internal
#' @useDynLib prospect
#' @author Antoine Stevens and Leonardo Ramirez-Lopez
fastDist <- function(X, Y, method) {
    .Call('prospect_fastDist', PACKAGE = 'prospect', X, Y, method)
}

#' @title A fast distance algorithm for a matrix and a vector written in C++ 
#' @usage 
#' fastDistV(X,Y,method)
#' @param X a \code{matrix}
#' @param Y a \code{vector}
#' @param method a \code{string} with possible values "euclid", "cor", "cosine"
#' @return a distance \code{vector}
#' @author Antoine Stevens and Leonardo Ramirez-Lopez
#' @keywords internal 
#' @useDynLib prospect
fastDistV <- function(X, Y, method) {
    .Call('prospect_fastDistV', PACKAGE = 'prospect', X, Y, method)
}

#' @title Resample to given band position and fwhm
#' @description
#' Resample, written in C++
#' @param X matrix to resample
#' @param wav a numeric \code{vector} giving the original band positions
#' @param new_wav a numeric \code{vector} giving the new band positions
#' @param fwhm numeric \code{vector} giving the full width half maximums of the new band positions.
#' @keywords internal
#' @useDynLib prospect
ResampleCppM <- function(X, wav, new_wav, fwhm) {
    .Call('prospect_ResampleCppM', PACKAGE = 'prospect', X, wav, new_wav, fwhm)
}

ResampleCppV <- function(X, wav, new_wav, fwhm) {
    .Call('prospect_ResampleCppV', PACKAGE = 'prospect', X, wav, new_wav, fwhm)
}

